"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import utilities.string

class CaseConverterTestCase(unittest.TestCase):
	def test_convert_to_snake_case(self):
		self.assertEqual(utilities.string.CaseConverter.convert_to_snake_case("CamelCase"), "camel_case")
		self.assertEqual(utilities.string.CaseConverter.convert_to_snake_case("notcamelcase"), "notcamelcase")
		self.assertEqual(utilities.string.CaseConverter.convert_to_snake_case(""), "")

	def test_convert_to_camel_case(self):
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case("snake_case"), "SnakeCase")
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case("_snake_case"), "SnakeCase")
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case("snake__case"), "SnakeCase")
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case("__snake_case"), "SnakeCase")
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case("snake"), "Snake")
		self.assertEqual(utilities.string.CaseConverter.convert_to_camel_case(""), "")
