"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import utilities.string

class PluralizerTestCase(unittest.TestCase):
	def test_pluralize(self):
		self.assertEqual(utilities.string.Pluralizer.pluralize("life"), "lives")
		self.assertEqual(utilities.string.Pluralizer.pluralize("play"), "plays")
		self.assertEqual(utilities.string.Pluralizer.pluralize("study"), "studies")
		self.assertEqual(utilities.string.Pluralizer.pluralize("attach"), "attaches")
		self.assertEqual(utilities.string.Pluralizer.pluralize("wash"), "washes")
		self.assertEqual(utilities.string.Pluralizer.pluralize("pass"), "passes")
		self.assertEqual(utilities.string.Pluralizer.pluralize("radius"), "radii")
		self.assertEqual(utilities.string.Pluralizer.pluralize("s"), "ss")
		self.assertEqual(utilities.string.Pluralizer.pluralize("alias"), "aliases")
