"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import utilities.design_pattern.singleton

class SingletonTestCase(unittest.TestCase):
	def test_singleton_initialization(self):
		self.assertEqual(utilities.design_pattern.singleton.Singleton.instance, None)

	def test_instances(self):
		class DummySingleton(utilities.design_pattern.singleton.Singleton):
			pass

		class AnotherDummySingleton(utilities.design_pattern.singleton.Singleton):
			pass

		self.assertEqual(type(DummySingleton.instance), DummySingleton)
		self.assertEqual(type(AnotherDummySingleton.instance), AnotherDummySingleton)

	def test_instantiation(self):
		class DummySingleton(utilities.design_pattern.singleton.Singleton):
			pass

		success = False

		try:
			dummy_singleton_object = DummySingleton()
		except utilities.design_pattern.singleton.exception.InstantiationError:
			success = True

		self.assertTrue(success)
