"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class CaseConverter:
	@staticmethod
	def convert_to_snake_case(string):
		"""
		Converts a CamelCase string to snake_case
		"""
		result = ""

		if len(string) > 0:
			token = string[0].lower()

			for i in range(1, len(string)):
				if string[i].isupper() and string[i - 1].islower():
					result += token + "_"
					token = string[i].lower()
				else:
					token += string[i].lower()

			result += token

		return result

	@staticmethod
	def convert_to_camel_case(string):
		"""
		Converts a snake_case string to CamelCase
		"""
		result = ""

		for token in string.split("_"):
			result += token.capitalize()

		return result
