"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from singleton_metaclass import SingletonMetaclass

class Singleton(object):
	__metaclass__ = SingletonMetaclass
