"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import exception

class SingletonMetaclass(type):
	_instance = None

	@property
	def instance(cls):
		return cls._instance

	def __init__(cls, name, bases, dct):
		type.__init__(cls, name, bases, dct)

		if cls.__module__ != "utilities.design_pattern.singleton.singleton":
			def instantiation_blocker(self):
				raise exception.InstantiationError("Singleton classes can't be instantiated.")

			cls._instance = cls()
			cls.__init__ = instantiation_blocker
